<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \App\Entities\Product implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'id', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'productName', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'description', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'image', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'productCountryId', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'productProviderId', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'metaTitle', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'metaKeywords', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'metaDescription', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'isActive', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'deleted', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'createdAt', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'productX', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'productSolutionX', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'productTypeX', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'productDetails', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'productImage'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'id', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'productName', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'description', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'image', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'productCountryId', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'productProviderId', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'metaTitle', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'metaKeywords', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'metaDescription', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'isActive', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'deleted', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'createdAt', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'productX', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'productSolutionX', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'productTypeX', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'productDetails', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'productImage'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Product $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductName', []);

        return parent::getProductName();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductName($productName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductName', [$productName]);

        return parent::setProductName($productName);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductCountryId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductCountryId', []);

        return parent::getProductCountryId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductCountryId($productCountryId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductCountryId', [$productCountryId]);

        return parent::setProductCountryId($productCountryId);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetaTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetaTitle', []);

        return parent::getMetaTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setMetaTitle($metaTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetaTitle', [$metaTitle]);

        return parent::setMetaTitle($metaTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetaKeywords()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetaKeywords', []);

        return parent::getMetaKeywords();
    }

    /**
     * {@inheritDoc}
     */
    public function setMetaKeywords($metaKeywords)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetaKeywords', [$metaKeywords]);

        return parent::setMetaKeywords($metaKeywords);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetaDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetaDescription', []);

        return parent::getMetaDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setMetaDescription($metaDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetaDescription', [$metaDescription]);

        return parent::setMetaDescription($metaDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeleted', []);

        return parent::getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeleted($deleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeleted', [$deleted]);

        return parent::setDeleted($deleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductDetails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductDetails', []);

        return parent::getProductDetails();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductDetails($productDetails)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductDetails', [$productDetails]);

        return parent::setProductDetails($productDetails);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductX()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductX', []);

        return parent::getProductX();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductX($productX)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductX', [$productX]);

        return parent::setProductX($productX);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductSolutionX()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductSolutionX', []);

        return parent::getProductSolutionX();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductSolutionX($productSolutionX)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductSolutionX', [$productSolutionX]);

        return parent::setProductSolutionX($productSolutionX);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductTypeX()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductTypeX', []);

        return parent::getProductTypeX();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductTypeX($productTypeX)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductTypeX', [$productTypeX]);

        return parent::setProductTypeX($productTypeX);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductProviderId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductProviderId', []);

        return parent::getProductProviderId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductProviderId($productProviderId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductProviderId', [$productProviderId]);

        return parent::setProductProviderId($productProviderId);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductImage', []);

        return parent::getProductImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductImage($productImage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductImage', [$productImage]);

        return parent::setProductImage($productImage);
    }

    /**
     * {@inheritDoc}
     */
    public function getisActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getisActive', []);

        return parent::getisActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsActive($isActive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsActive', [$isActive]);

        return parent::setIsActive($isActive);
    }

}
